version: 2

sources:
  - name: nytaxi
    schema: nytaxi
    tables:
      - name: yellow_tripdata_raw
        identifier: yellow_tripdata_raw
      - name: taxi_zone_lookup_raw
        identifier: taxi_zone_lookup_raw
models:
  - name: stg_zone
    description: This model cleans up location data

  - name: stg_trip
    description: This model cleans up trip data
  
  - name: stg_time
    description:  This model cleans up time data

  - name: stg_taxi
    description: This model cleans up taxi data
